### ISSUE TITLE
Error when starting eyeliner

### ISSUE THREAD

**Issue by fjell-dev** [dustinlacewell/eyeliner#1]
Hi,
thanks for the package (and also introducing me to the straight.el package, I did not know about it before).
I'm running emacs 27.0.50 (emacs-snapshot) on Kubuntu 18.04 and there is an error message when starting eyeliner.
"Error (use-package): eyeliner/:catch: Symbol’s function definition is void: pipeline"
Could you check what could be the source of the error message? Thanks a lot.

**Comment by dustinlacewell** [comment]
Hey, I think this was fixed some time ago. So sorry for the lack of communication! I'm gonna close this but feel free to open it or any other issue.
